### ISSUE TITLE
_TILT_CALIBRATE macro doesn't work as it should.

### ISSUE THREAD

**Issue by AMFkuna** [Frix-x/klippain#315] opened 2023-10-07 08:02 UTC
### Klippain branch

- [X] I confirm using the main branch

### Version

v4.1.1

### Describe the bug and expected behavior

In this macro, the conditions for detecting the tilting state are incorrectly defined.
When QGL is done, it starts again on the next print.

original - not working correctly
{% if printer.quad_gantry_level.applied|lower == 'false' or FORCE_OPERATION %}
{% if printer.z_tilt.applied|lower == 'false' or FORCE_OPERATION %}

should be - working
{% if printer.quad_gantry_level.applied|lower == 'false' or FORCE_OPERATION|lower == 'true' %}
{% if printer.z_tilt.applied|lower == 'false' or FORCE_OPERATION|lower == 'true' %}

**Comment by Frix-x** [comment] 2023-10-07 13:36
This is a duplicate of issue #214 
And I definitely need to implement the fix. I'll do it for the next version, thanks for the reminder ^^

**Closed by Frix-x** 2023-10-07 13:36 UTC
Labels: bug, duplicate
